# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_details',
            new_name='User_detail',
        ),
    ]
