# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0002_details_event_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='event_category',
            field=models.CharField(default=1000, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='event_date',
            field=models.CharField(default=250, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='event_location',
            field=models.CharField(default=1000, max_length=1000),
            preserve_default=False,
        ),
    ]
