# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_details', '0003_auto_20170703_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='event_date',
            field=models.DateTimeField(),
        ),
    ]
